# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b2db29c21703f46fa9e741fe1d21e77ef1793adb9f1b983d7db5ae2e9b674efc6461d9872c10c5114a51f0419cd5c6075ef4a635ee4bfe09c9c57ef9391d45

test:
  secret_key_base: 64a3d41946e3419d7a7e5c1de849b17fbb7def092534e986359da7e56e6a41b7220a3589e7409f0c5c05da17ea2814b8614fa6427af384842adefd407ec25746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
